name: Build and deploy

on:
    push:
        branches:
            - master
        paths-ignore:
            - '**/README.md'
    pull_request:
        branches:
            - master
        paths-ignore:
            - 'README.md'
    workflow_dispatch:
    schedule:
        - cron:  '0 2 * * 1' # Once a week at 02:00 on Monday

jobs:
    build_and_deploy:
        name: Build and deploy

        runs-on: ubuntu-latest

        steps:

            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2

            -   name: Set up Docker Buildx
                id: buildx
                uses: docker/setup-buildx-action@v2

            -   name: Build and test
                if: github.ref != 'refs/heads/master'
                run: |
                    make LOCAL=1
                    make php

            -   name: Log in to the Container registry
                if: github.ref == 'refs/heads/master'
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Deploy
                if: github.ref == 'refs/heads/master'
                run: make DEPLOY=1 php
